### ISSUE TITLE
unable to read from socket [10045]

### ISSUE THREAD

**Issue by lee32768** [carbonsphere/UHPPOTE#3]
Hey there,
I'm working towards a remote unlock solution via my webserver.  I keep getting the error below, regardless of the command issued ('get_ripp','dev_status','open_door').  I'm starting to wonder if it's my serial number and I just don't have a connection.  There's a number on the board and there's the mac address - I've entered both in various degrees and directions.  My server is IIS with PHP7.

thanks for any help,
lee

Padding 56 Send the following command to network 179200004C1439190000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 Sending.... Listening for return status 
Warning: socket_recv(): unable to read from socket [10045]: The attempted operation is not supported for the type of object referenced. in C:\xxx\yyy\zzz.php on line 64
Receive socket Error: [10045] The attempted operation is not supported for the type of object referenced.

**Comment by carbonsphere** [comment]
this probably is caused by your environment. This script was tested in OSX & Linux environment. 

Follow serial format 
/*
 * Remember to set your serial number
 * usually the last 4 bytes of your board's MAC address
 * EX:  00:11:22:33:44:55  then the Serial Number = 22334455
 */
Is your board mac like this?   xx:xx:4c:14:39:19 If so, then by using the following command should construct a valid packet.
$a->setSn("4C143919");

**Comment by carbonsphere** [comment]
Try run "search.php"

It will broad cast search packet to your network (If your windows environment is working) and the device should echo back a identification.
